name: Contracts CI/CD

env:
  FOUNDRY_PROFILE: "ci"

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "contracts/**"
  workflow_dispatch:

jobs:
  common-steps:
    name: Common Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_PULL_TOKEN }}
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache Foundry artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.foundry/cache
          key: ${{ runner.os }}-foundry-cache
          restore-keys: |
            ${{ runner.os }}-foundry-cache

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Common Setup
        uses: ./.github/workflows/your-repo-name/.github/actions/common-steps

      - name: Ensure files are formatted
        working-directory: ./contracts
        run: forge fmt src/ test/ script/ --check

  build:
    name: Build Contracts
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Common Setup
        uses: ./.github/workflows/your-repo-name/.github/actions/common-steps

      - name: Build contracts and print sizes
        working-directory: ./contracts
        run: forge build --sizes

      - name: Add build summary
        run: |
          echo "## Build Result" >> $GITHUB_STEP_SUMMARY
          echo "Build completed successfully. Contract sizes:" >> $GITHUB_STEP_SUMMARY
          forge build --sizes >> $GITHUB_STEP_SUMMARY

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Common Setup
        uses: ./.github/workflows/your-repo-name/.github/actions/common-steps

      - name: Generate fuzz seed
        run: echo "FOUNDRY_FUZZ_SEED=$(( $(date +%s) - $(date +%s) % 604800 ))" >> $GITHUB_ENV

      - name: Run tests
        working-directory: ./contracts
        run: forge test --gas-report

      - name: Add test summary
        run: |
          echo "## Test Result" >> $GITHUB_STEP_SUMMARY
          echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY
